tc: 100 #total number of connections.
lm: "Hello, server!" #the message which needs to be sent.
mi: 0 #message interval. data type is duration. example values, 1s , 30m, 1h, etc
am: "AUTH user:password" #Auth Message
wba: 5s #wait before sending authorization.
waa: 2s #wait after sending authorization.
rups: 1 #ramp up per second
outfile: "" #if empty will open tview, else will write the output to given file.
srp: 10 #percentage of connections that will be slow readers
srd: 200ms #duration by which slow readers will delay reading messages. Default 100ms if srp is greater than 0